parameters:
  BARBuildId: ''
  PromoteToChannelIds: ''

  enableSourceLinkValidation: false
  enableSigningValidation: true
  enableNugetValidation: true
  publishInstallersAndChecksums: true
  
  # These parameters let the user customize the call to sdk-task.ps1 for publishing
  # symbols & general artifacts as well as for signing validation
  symbolPublishingAdditionalParameters: ''
  artifactsPublishingAdditionalParameters: ''
  signingValidationAdditionalParameters: ''

  # Which stages should finish execution before post-build stages start
  validateDependsOn:
  - build

stages:
  - stage: publish
    dependsOn: ${{ parameters.publishDependsOn }}
    variables:
      - template: /eng/publishing/v3/common-variables.yml
    displayName: Publishing
    jobs:
    - template: /eng/publishing/v3/setup-maestro-vars.yml
      parameters:
        BARBuildId: ${{ parameters.BARBuildId }}
        PromoteToChannelIds: ${{ parameters.PromoteToChannelIds }}
        
    - template: /eng/publishing/v3/publish-assets.yml
      parameters:
        PromoteToChannelIds: ${{ parameters.PromoteToChannelIds }}
        publishInstallersAndChecksums: ${{ parameters.publishInstallersAndChecksums }}
        artifactsPublishingAdditionalParameters: ${{ parameters.artifactsPublishingAdditionalParameters }}
        symbolPublishingAdditionalParameters: ${{parameters.symbolPublishingAdditionalParameters}}
